# Generated by Django 5.1 on 2024-09-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('encrypted_message', models.TextField(blank=True, null=True)),
                ('key', models.TextField(blank=True, null=True)),
                ('encryption_type', models.CharField(choices=[('AES', 'AES'), ('Fernet', 'Fernet'), ('RSA', 'RSA'), ('ECC', 'ECC')], max_length=10)),
            ],
        ),
    ]
